### ISSUE TITLE
Join on Main

### ISSUE THREAD

**Issue by DrMikeyS** [tango-3/COVIDVaccinePatientSlips#7]
Hi @miketrebilcock ,

Would you like to take over the main branch?

Mike

**Comment by miketrebilcock** [comment]
I'm happy to take it on Mike.

**Comment by miketrebilcock** [comment]
@DrMikeyS not sure the best way to move it forward. PR my commits into the https://github.com/DrMikeyS/COVIDVaccinePatientSlips repo, or leave that repo as it is with a pointer to this one? What do you think?

**Comment by DrMikeyS** [comment]
Actually, let's stick with the pointer. That way your handle gets the credit on an ongoing basis.

**Comment by miketrebilcock** [comment]
@DrMikeyS if you leave me with the access you just granted, I'm happy to keep an eye on issues raised there and close them as required.

**Comment by miketrebilcock** [comment]
@DrMikeyS, you made an awesome tool by the way. I would never have thought about putting control characters into a QR Code - genius!
